### ISSUE TITLE
missing field `pages_path`

### ISSUE THREAD

**Issue by szabgab** [wezm/pkb#27]
I cloned the repo, copied `Rocket.sample.toml` to `Rocket.toml`, created a folder called `pages` with a file called `home.md` and ran `cargo run`.

After compilation I got:

```
Error: Failed to extract valid configuration.
   >> missing field `pages_path`
thread 'main' panicked at src/web.rs:81:47:
no settings in state
```

Did I do something incorrectly?

```
$ rustc -vV
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6
```

**Comment by wezm** [comment]
Hmm, I just followed the same steps and it worked. Did you run `cargo run` from the top-level of the repo (where `Rocket.toml` is)?

**Comment by szabgab** [comment]
Oh, I just found the problem I had and I am embarrassed.
I had `export ROCKET_CONFIG=Debug.toml` in my `~/.bash_profile`.

I knew it wasn't a good solution when I used that, but now it really bite me.

Removing that obviously solved the problem I had.

Sorry for the false report and the waste of time.

**Comment by wezm** [comment]
No worries, glad you found the source of the issue.
